#spring:
#application:
#name: eureka-server

#nested
#high readability
#String,Boolean,numbers
#lightweight
#list (-) reason for use yml files to docker like advanced technologies

server:
  port: 8761


  eureka:
    client:
      #server should not register itself as a service (client)
      register-with-eureka: false
      #prevent fetching its own service list
      fetch-registry: false